### PR TITLE
feat: Implement maxStack

### LINKED ISSUE #104: [Feature Request] No stacking notifications
First of all, this notification project is very easy to use and pretty CSS. I just started using it for my project.

I just have one feature that I want to have is, not stacking the notifications.
When there is a new notification, I want to close the current notification and display a new one.

Workaround for this feature is using `dismissAll()`, but it still makes stacking notifications before dismissing an old notification.

Demo: https://jsfiddle.net/2jg0wv4m/

Is there an alternative way to replace opened notification?

### PR DESCRIPTION
**Pull request by chrisleekr**
- Added new option `maxStack`

Resolves #104

### CODE REVIEW

**Comment by caroso1222** [comment]
Hey! thanks for your contribution. I'll take a detailed look at this within the next week.

**Comment by paulocoutinhox** [comment]
Can you solve this?

**Comment by vicenterusso** [comment]
Waiting for this being accepted

**Comment by paulocoutinhox** [comment]
There is a new release with this?

**Pull request closed without merging**
